### ISSUE TITLE
Theme standard

### ISSUE THREAD

**Issue by dingo-d** [WordPress/wporg-code-analysis#38]
Not sure if you are aware of it, but we have a theme standard: https://github.com/WPTT/WPThemeReview

It would be cool if that priject didn't die off just because it was replaced with something else without checking. A lot of volunteer hours went into creating that.

**Comment by iandunn** [comment]
Hi @dingo-d 👋🏻 

`MinimalThemeStandard` in this repo is heavily dependent on `WPThemeReview` (see 0f977a23e2215289116946845ec23cc3f316367d). Do you have any thoughts on ways to improve on that, or better utilize the existing standard?

**Comment by dingo-d** [comment]
Oh, I haven't seen this 👍🏼  I just saw tons of other additions to the theme ruleset and assumed that you didn't have used it.

Still, It would be better to add all the theme additions directly in the wpthemreview ruleset (if they apply), so you'd only need to include this ruleset, no extra additions or exclusions.

**Comment by iandunn** [comment]
I agree (#34) 👍🏻 

I think they're just separate in the short-term so we can quickly test out & iterate things that may or may not be good long-term.

**Comment by dingo-d** [comment]
Cool, thanks for the explanation 👍🏼
