### ISSUE TITLE
UnescapedOutputParameter doesn't terminate at ?>

### ISSUE THREAD

**Issue by dd32** [WordPress/wporg-code-analysis#76]
With code like this, the error output incorrectly continues to the end of the string.
```
<img src="<?php echo esc_url_raw( $url ) ?>" alt="<?php echo esc_html( $alt ) ?>"/>
```

eg:
```
WARNING WordPressDotOrg.sniffs.OutputEscaping.UnescapedOutputParameter in file.php
Unescaped parameter esc_url_raw( $url ) ?>" alt="<?php echo esc_html( $alt ) ?>"/> used in echo
```

It appears not to terminate by `?>` and only by `;`.

Upon testing via #77 it appears that it's not that it's not terminating, it's that it can't even find the match..

**Comment by tellyworth** [comment]
I updated #77 with a fix. Unit tests pass now, does that look like it's complete?

The bug was that it was seeking for `;` or `,` or `)` as the end of an expression, but not `?>`. It probably worked fine before for inline code that included a terminating semicolon.

**Comment by dd32** [comment]
> Unit tests pass now, does that look like it's complete?

I would expect so.

Upon looking at your commit, it seems like that's what I was hunting for, but wasn't able to spot.
